### ISSUE TITLE
Guidance for using dotnet-script in Azure Pipelines

### ISSUE THREAD

**Issue by ssippe** [filipw/dotnet-script#577]
Hi,

Thanks for dotnet-script. It's fantastic.

I wanted to use dotnet-script in my azure pipelines and I managed to get something working. My yml configuration looks like this:

```
steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'update dotnet-script -g'
    displayName: 'install dotnet-script'  

  - task: CmdLine@2 
    inputs:      
      script : |
        dotnet script myScript.csx
    displayName: "run myScript.csx"
```

I thought this might be helpful for others trying to do the same thing. If there's a better way to do it, please let me know.

Cheers
